/* eslint-disable react/no-unescaped-entities */
import Head from "next/head";
import {
  
  AiFillLinkedin,
  
  AiFillGithub,
  AiFillGoogleCircle
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";


import Image from "next/legacy/image";

import coding from "../public/coding.webp";
import frontend from "../public/frontend.png";
import backend from "../public/backend.jpg";
import restaurant from "../public/restaurant.jpeg";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Harsh Sharma Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">developedbyharsh</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="https://drive.google.com/file/d/1z2SwUWE8PUngT4fEgNNZaW9j61J3rNgu/view?usp=sharing"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
            Hii there,
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
            My name is Harsh Sharma.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
            A Software Developer with a passion for learning and creating.
            
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <AiFillGoogleCircle/>
              <a href="https://www.linkedin.com/in/harsh-sharma-5112b4185/"><AiFillLinkedin /></a>
              <a href="https://github.com/harsh-sharma-ind"><AiFillGithub /></a>
              
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={deved} layout="fill" objectFit="cover" alt=""/>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Education And Skills</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            I've done <span className="text-teal-500"> B.Tech </span> in Electrical & Electronics Engineering <span className="text-teal-500"> ( 2018-2022 ) </span> from Oriental 
            Institute of Science and Technology, Bhopal with 
              <span className="text-teal-500"> 8.46 CGPA. </span>
              
            </p>
            
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={coding} width={100} height={100} alt=""/>
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Programming Languages And IT Constructs
              </h3>
              
              <p className="text-gray-800 py-1">C++</p>
              <p className="text-gray-800 py-1">Java</p>
              <p className="text-gray-800 py-1">Python</p>
              <p className="text-gray-800 py-1">OOPS</p>
              <p className="text-gray-800 py-1">Data Structures and Algorithms</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={frontend} width={100} height={100} alt=""/>
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Frontend Development
              </h3>
              
              <p className="text-gray-800 py-1">HTML</p>
              <p className="text-gray-800 py-1">CSS</p>
              <p className="text-gray-800 py-1">Java Script</p>
              <p className="text-gray-800 py-1">React JS</p>
              <p className="text-gray-800 py-1">Next JS</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={backend} width={100} height={100} alt=""/>
              <h3 className="text-lg font-medium pt-8 pb-2 ">Backend Development</h3>
              
              <p className="text-gray-800 py-1">Node JS</p>
              <p className="text-gray-800 py-1">Express JS</p>
              <p className="text-gray-800 py-1">Mongo DB</p>
              
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Projects</h3>
            
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={restaurant}
                bg-opacity-50
                alt=""
              />
            </div>
            <div className="basis-1/3 flex-1">
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
            Food Cart WebApp
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
            Design and development of a web application from scratch for food cart, 
            user interface components and logical to add and remove products from cart and to generate bill. 
            </p>

            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
            <span className="text-teal-500"> Skills : </span>
            React JS, Context API, React States, React Hooks, HTML, CSS, JSX, JavaScript

            </p>

            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
            <span className="text-teal-500"> Link : </span>
            <a href="https://assignmentharsh.netlify.app/">Food Cart WebApp</a>

            </p>
            </div>
            
          </div>
        </section>
      </main>
    </div>
  );
}